_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.10.16
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
algorithm:
    value:
        clip_param: 0.2
        desired_kl: 0.01
        entropy_coef: 0.01
        gamma: 0.99
        lam: 0.95
        learning_rate: 0.001
        max_grad_norm: 1
        num_learning_epochs: 5
        num_mini_batches: 4
        schedule: adaptive
        use_clipped_value_loss: true
        value_loss_coef: 1
max_iterations:
    value: 1000
motion_file:
    value: data/pace.npy
num_envs:
    value: 256
policy:
    value:
        activation: elu
        actor_hidden_dims:
            - 512
            - 256
            - 128
        critic_hidden_dims:
            - 512
            - 256
            - 128
        init_noise_std: 1
reward_scales:
    value:
        action_rate: -4e-05
        base_height: -0.1
        chassis_height: 1
        forward_motion: 1
        joint_pose_matching: 4
        leg_symmetry: 3
        legs_apart: 2.5
        lin_vel_z: -0.02
        similar_to_default: -0.001
        tracking_ang_vel: 0.016
        tracking_lin_vel: 0.016
seed:
    value: 1
